# Generated by Django 3.1.3 on 2020-12-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=20)),
                ('redirect_url', models.TextField()),
                ('tracking_url', models.CharField(max_length=20)),
            ],
        ),
    ]
