# Generated by Django 3.1.3 on 2020-12-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_url', models.CharField(max_length=20)),
                ('short_url', models.CharField(max_length=20)),
                ('ip_address', models.TextField()),
                ('browser', models.TextField()),
                ('os', models.TextField()),
                ('device_type', models.TextField()),
                ('device', models.TextField()),
            ],
        ),
    ]
