# Generated by Django 3.1.3 on 2020-12-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyServer', '0002_trackingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='time',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
